/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fingerlime.gui;

import fingerlime.gui.contribuyentes.FrmContribuyentes;
import fingerlime.gui.form606.Frm606;


/**
 *
 * @author victor
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelTItulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBotonesTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        panelIconos = new javax.swing.JPanel();
        btn608 = new javax.swing.JToolBar();
        btnContribuyentes = new javax.swing.JButton();
        btn606 = new javax.swing.JButton();
        btn607 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAjustes = new javax.swing.JButton();
        panelTituloIconos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FingerLime");
        setMinimumSize(new java.awt.Dimension(374, 250));
        setPreferredSize(new java.awt.Dimension(865, 535));

        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelSuperior.setPreferredSize(new java.awt.Dimension(0, 60));
        panelSuperior.setLayout(new java.awt.GridLayout(1, 0));

        panelTItulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        panelTItulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 131, 37));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/lime_32.png"))); // NOI18N
        jLabel1.setToolTipText("FingerLime");
        panelTItulo.add(jLabel1);

        panelSuperior.add(panelTItulo);

        panelBotonesTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 105, 138));
        jLabel2.setText("Víctor M. Brito");
        panelBotonesTitulo.add(jLabel2);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/exit_16.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelBotonesTitulo.add(btnSalir);

        panelSuperior.add(panelBotonesTitulo);

        PanelPrincipal.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelCentral.setLayout(new java.awt.BorderLayout());

        panelIconos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelIconos.setPreferredSize(new java.awt.Dimension(1000, 200));

        btn608.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn608.setFloatable(false);
        btn608.setRollover(true);

        btnContribuyentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/group_32.png"))); // NOI18N
        btnContribuyentes.setText("Contribuyentes");
        btnContribuyentes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnContribuyentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContribuyentes.setFocusable(false);
        btnContribuyentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContribuyentes.setIconTextGap(5);
        btnContribuyentes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContribuyentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContribuyentesActionPerformed(evt);
            }
        });
        btn608.add(btnContribuyentes);

        btn606.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/expensive_32.png"))); // NOI18N
        btn606.setText("Remisiónes CyG (606)");
        btn606.setToolTipText("Remisiones de Costos y Gastos");
        btn606.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btn606.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn606.setFocusable(false);
        btn606.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn606.setIconTextGap(5);
        btn606.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn606.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn606ActionPerformed(evt);
            }
        });
        btn608.add(btn606);

        btn607.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/sale_32.png"))); // NOI18N
        btn607.setText("Remisiones VyO (607)");
        btn607.setToolTipText("Remisiones de Ventas y Operaciones");
        btn607.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btn607.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn607.setFocusable(false);
        btn607.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn607.setIconTextGap(5);
        btn607.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn608.add(btn607);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/shopping-cart-cancel_32png.png"))); // NOI18N
        jButton1.setText("Comp. Anulados (608)");
        jButton1.setToolTipText("Remisiones de Comprobantes Anulados");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(5);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn608.add(jButton1);

        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/settings_32.png"))); // NOI18N
        btnAjustes.setText("Configuraciones");
        btnAjustes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjustes.setFocusable(false);
        btnAjustes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAjustes.setIconTextGap(5);
        btnAjustes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn608.add(btnAjustes);

        javax.swing.GroupLayout panelIconosLayout = new javax.swing.GroupLayout(panelIconos);
        panelIconos.setLayout(panelIconosLayout);
        panelIconosLayout.setHorizontalGroup(
            panelIconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIconosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn608, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE))
        );
        panelIconosLayout.setVerticalGroup(
            panelIconosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn608, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        panelCentral.add(panelIconos, java.awt.BorderLayout.CENTER);

        panelTituloIconos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(57, 105, 138)));
        panelTituloIconos.setPreferredSize(new java.awt.Dimension(1000, 35));
        panelTituloIconos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 105, 138));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/home_24.png"))); // NOI18N
        jLabel3.setText("Inicio");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelTituloIconos.add(jLabel3);

        panelCentral.add(panelTituloIconos, java.awt.BorderLayout.PAGE_START);

        PanelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnContribuyentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContribuyentesActionPerformed
        FrmContribuyentes frm = new FrmContribuyentes();
        frm.setVisible(true);
    }//GEN-LAST:event_btnContribuyentesActionPerformed

    private void btn606ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn606ActionPerformed
        Frm606 frm = new Frm606();
        frm.setVisible(true);
    }//GEN-LAST:event_btn606ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btn606;
    private javax.swing.JButton btn607;
    private javax.swing.JToolBar btn608;
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnContribuyentes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelBotonesTitulo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelIconos;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTItulo;
    private javax.swing.JPanel panelTituloIconos;
    // End of variables declaration//GEN-END:variables
}
