/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fingerlime.gui;

import fingerlime.gui.contribuyentes.FrmContribuyentes;
import fingerlime.gui.form606.Frm606;


/**
 *
 * @author victor
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelTItulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBotonesTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        panelIconos = new javax.swing.JPanel();
        btnContribuyentes = new javax.swing.JButton();
        btn606 = new javax.swing.JButton();
        btn607 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAjustes = new javax.swing.JButton();
        panelTituloIconos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelDetalle = new javax.swing.JPanel();
        lblDetalle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FingerLime");
        setMinimumSize(new java.awt.Dimension(374, 250));
        setPreferredSize(new java.awt.Dimension(865, 535));

        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelSuperior.setPreferredSize(new java.awt.Dimension(0, 60));
        panelSuperior.setLayout(new java.awt.GridLayout(1, 0));

        panelTItulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        panelTItulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 131, 37));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/lime_32.png"))); // NOI18N
        jLabel1.setToolTipText("FingerLime");
        panelTItulo.add(jLabel1);

        panelSuperior.add(panelTItulo);

        panelBotonesTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 105, 138));
        jLabel2.setText("Víctor M. Brito");
        panelBotonesTitulo.add(jLabel2);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/exit_16.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelBotonesTitulo.add(btnSalir);

        panelSuperior.add(panelBotonesTitulo);

        PanelPrincipal.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelCentral.setLayout(new java.awt.BorderLayout());

        panelInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelInicio.setPreferredSize(new java.awt.Dimension(1000, 200));
        panelInicio.setLayout(new javax.swing.BoxLayout(panelInicio, javax.swing.BoxLayout.LINE_AXIS));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        panelIconos.setLayout(flowLayout1);

        btnContribuyentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/group_32.png"))); // NOI18N
        btnContribuyentes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnContribuyentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContribuyentes.setFocusable(false);
        btnContribuyentes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnContribuyentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContribuyentes.setIconTextGap(5);
        btnContribuyentes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContribuyentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContribuyentesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContribuyentesMouseExited(evt);
            }
        });
        btnContribuyentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContribuyentesActionPerformed(evt);
            }
        });
        panelIconos.add(btnContribuyentes);

        btn606.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/expensive_32.png"))); // NOI18N
        btn606.setToolTipText("Remisiones de Costos y Gastos (606)");
        btn606.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btn606.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn606.setFocusable(false);
        btn606.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn606.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn606.setIconTextGap(5);
        btn606.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn606.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn606MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn606MouseExited(evt);
            }
        });
        btn606.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn606ActionPerformed(evt);
            }
        });
        panelIconos.add(btn606);

        btn607.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/sale_32.png"))); // NOI18N
        btn607.setToolTipText("Remisiones de Ventas y Operaciones (607)");
        btn607.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btn607.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn607.setFocusable(false);
        btn607.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn607.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn607.setIconTextGap(5);
        btn607.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelIconos.add(btn607);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/shopping-cart-cancel_32png.png"))); // NOI18N
        jButton1.setToolTipText("Remisiones de Comprobantes Anulados (608)");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setHideActionText(true);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(5);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelIconos.add(jButton1);

        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/settings_32.png"))); // NOI18N
        btnAjustes.setToolTipText("Configuracion");
        btnAjustes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjustes.setFocusable(false);
        btnAjustes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAjustes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAjustes.setIconTextGap(5);
        btnAjustes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelIconos.add(btnAjustes);

        panelInicio.add(panelIconos);

        panelCentral.add(panelInicio, java.awt.BorderLayout.CENTER);

        panelTituloIconos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(57, 105, 138)));
        panelTituloIconos.setPreferredSize(new java.awt.Dimension(1000, 35));
        panelTituloIconos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 105, 138));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/home_24.png"))); // NOI18N
        jLabel3.setText("Inicio");
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelTituloIconos.add(jLabel3);

        panelCentral.add(panelTituloIconos, java.awt.BorderLayout.PAGE_START);

        panelDetalle.setPreferredSize(new java.awt.Dimension(849, 35));

        lblDetalle.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblDetalle.setForeground(new java.awt.Color(57, 105, 138));
        lblDetalle.setText("Detalle");
        panelDetalle.add(lblDetalle);

        panelCentral.add(panelDetalle, java.awt.BorderLayout.PAGE_END);

        PanelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnContribuyentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContribuyentesActionPerformed
        FrmContribuyentes frm = new FrmContribuyentes();
        frm.setVisible(true);
    }//GEN-LAST:event_btnContribuyentesActionPerformed

    private void btn606ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn606ActionPerformed
        Frm606 frm = new Frm606();
        frm.setVisible(true);
    }//GEN-LAST:event_btn606ActionPerformed

    private void btnContribuyentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContribuyentesMouseEntered
        lblDetalle.setText("Contribuyentes");
    }//GEN-LAST:event_btnContribuyentesMouseEntered

    private void btnContribuyentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContribuyentesMouseExited
        lblDetalle.setText("");
    }//GEN-LAST:event_btnContribuyentesMouseExited

    private void btn606MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn606MouseEntered
        lblDetalle.setText("Remisiones de Costos y Gastos (606)");
    }//GEN-LAST:event_btn606MouseEntered

    private void btn606MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn606MouseExited
        lblDetalle.setText("");
    }//GEN-LAST:event_btn606MouseExited

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btn606;
    private javax.swing.JButton btn607;
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnContribuyentes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JPanel panelBotonesTitulo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDetalle;
    private javax.swing.JPanel panelIconos;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTItulo;
    private javax.swing.JPanel panelTituloIconos;
    // End of variables declaration//GEN-END:variables
}
