/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fingerlime.gui.ajustes;

/**
 *
 * @author victor
 */
public class FrmAjustes extends javax.swing.JDialog {

    /**
     * Creates new form frmAjustes
     */
    public FrmAjustes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        panelTtulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelAcciones = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        panelUsuarios = new javax.swing.JPanel();
        panelTopUsuarios = new javax.swing.JPanel();
        txtBusquedaUsuarios = new javax.swing.JTextField();
        btnBuscarUsuarios = new javax.swing.JButton();
        paneTablaUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelDatos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelSuperior.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(57, 105, 138)));
        panelSuperior.setPreferredSize(new java.awt.Dimension(729, 40));
        panelSuperior.setLayout(new java.awt.GridLayout());

        panelTtulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 105, 138));
        jLabel1.setText("Ajustes");
        panelTtulo.add(jLabel1);

        panelSuperior.add(panelTtulo);

        panelAcciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/close_16.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        panelAcciones.add(btnCerrar);

        panelSuperior.add(panelAcciones);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setLayout(new javax.swing.BoxLayout(panelCentral, javax.swing.BoxLayout.LINE_AXIS));

        tabPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panelUsuarios.setLayout(new java.awt.BorderLayout());

        panelTopUsuarios.setPreferredSize(new java.awt.Dimension(655, 35));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        panelTopUsuarios.setLayout(flowLayout1);

        txtBusquedaUsuarios.setPreferredSize(new java.awt.Dimension(200, 27));
        txtBusquedaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaUsuariosActionPerformed(evt);
            }
        });
        panelTopUsuarios.add(txtBusquedaUsuarios);

        btnBuscarUsuarios.setText("Buscar");
        panelTopUsuarios.add(btnBuscarUsuarios);

        panelUsuarios.add(panelTopUsuarios, java.awt.BorderLayout.PAGE_START);

        paneTablaUsuarios.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        paneTablaUsuarios.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelUsuarios.add(paneTablaUsuarios, java.awt.BorderLayout.CENTER);

        tabPanel.addTab("Usuarios", panelUsuarios);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        tabPanel.addTab("Datos", panelDatos);

        panelCentral.add(tabPanel);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAjustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAjustes dialog = new FrmAjustes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuarios;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel paneTablaUsuarios;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTopUsuarios;
    private javax.swing.JPanel panelTtulo;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextField txtBusquedaUsuarios;
    // End of variables declaration//GEN-END:variables
}
