/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fingerlime.gui.ajustes;

import fingerlime.core.FormatoTxtContribuyente;
import fingerlime.models.ContribuyenteRaw;
import fingerlime.models.EjemploTask;
import fingerlime.tasks.TaskImportarContribuyentes;
import java.io.File;
import java.util.List;

/**
 *
 * @author victor
 */
public class FrmAjustes extends javax.swing.JDialog {

    /**
     * Creates new form frmAjustes
     */
    public FrmAjustes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public File archivoContribuyentes;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        panelSuperior = new javax.swing.JPanel();
        panelTtulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelAcciones = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        panelUsuarios = new javax.swing.JPanel();
        panelTopUsuarios = new javax.swing.JPanel();
        txtBusquedaUsuarios = new javax.swing.JTextField();
        btnBuscarUsuarios = new javax.swing.JButton();
        paneTablaUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelDatos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNombreArchivoContribuyentes = new javax.swing.JTextField();
        btnExplorarArchivoTXT = new javax.swing.JButton();
        pbgImportacionDatos = new javax.swing.JProgressBar();
        btnIniciarImportacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelSuperior.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(57, 105, 138)));
        panelSuperior.setPreferredSize(new java.awt.Dimension(729, 40));
        panelSuperior.setLayout(new java.awt.GridLayout(1, 0));

        panelTtulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 105, 138));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/settings_24.png"))); // NOI18N
        jLabel1.setText("Ajustes");
        panelTtulo.add(jLabel1);

        panelSuperior.add(panelTtulo);

        panelAcciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/close_16.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelAcciones.add(btnCerrar);

        panelSuperior.add(panelAcciones);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setLayout(new javax.swing.BoxLayout(panelCentral, javax.swing.BoxLayout.LINE_AXIS));

        tabPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panelUsuarios.setLayout(new java.awt.BorderLayout());

        panelTopUsuarios.setPreferredSize(new java.awt.Dimension(655, 35));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        panelTopUsuarios.setLayout(flowLayout1);

        txtBusquedaUsuarios.setPreferredSize(new java.awt.Dimension(200, 27));
        txtBusquedaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaUsuariosActionPerformed(evt);
            }
        });
        panelTopUsuarios.add(txtBusquedaUsuarios);

        btnBuscarUsuarios.setText("Buscar");
        panelTopUsuarios.add(btnBuscarUsuarios);

        panelUsuarios.add(panelTopUsuarios, java.awt.BorderLayout.PAGE_START);

        paneTablaUsuarios.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        paneTablaUsuarios.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelUsuarios.add(paneTablaUsuarios, java.awt.BorderLayout.CENTER);

        tabPanel.addTab("Usuarios", panelUsuarios);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(57, 105, 138)), "Importar datos desde TXT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        txtNombreArchivoContribuyentes.setEditable(false);
        txtNombreArchivoContribuyentes.setBackground(new java.awt.Color(241, 243, 244));

        btnExplorarArchivoTXT.setText("Examinar...");
        btnExplorarArchivoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplorarArchivoTXTActionPerformed(evt);
            }
        });

        pbgImportacionDatos.setForeground(new java.awt.Color(57, 105, 138));
        pbgImportacionDatos.setStringPainted(true);

        btnIniciarImportacion.setText("Iniciar");
        btnIniciarImportacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarImportacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombreArchivoContribuyentes, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExplorarArchivoTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIniciarImportacion))
                    .addComponent(pbgImportacionDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArchivoContribuyentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExplorarArchivoTXT)
                    .addComponent(btnIniciarImportacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbgImportacionDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        tabPanel.addTab("Datos", panelDatos);

        panelCentral.add(tabPanel);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaUsuariosActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnExplorarArchivoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplorarArchivoTXTActionPerformed
        this.fileChooser.showOpenDialog(this);
        this.archivoContribuyentes = fileChooser.getSelectedFile();
        if (archivoContribuyentes != null) {
            this.txtNombreArchivoContribuyentes.setText(archivoContribuyentes.getPath());
        }
    }//GEN-LAST:event_btnExplorarArchivoTXTActionPerformed

    private void btnIniciarImportacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarImportacionActionPerformed
        this.getpbgImportacionDatos().setIndeterminate(true);
        this.pbgImportacionDatos.setString("Cargando archivo");
        Runnable task = new TaskImportarContribuyentes(this);
        Thread t = new Thread(task);
        t.start();
    }//GEN-LAST:event_btnIniciarImportacionActionPerformed

public javax.swing.JProgressBar getpbgImportacionDatos(){
    return this.pbgImportacionDatos;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuarios;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExplorarArchivoTXT;
    private javax.swing.JButton btnIniciarImportacion;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel paneTablaUsuarios;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTopUsuarios;
    private javax.swing.JPanel panelTtulo;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JProgressBar pbgImportacionDatos;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextField txtBusquedaUsuarios;
    private javax.swing.JTextField txtNombreArchivoContribuyentes;
    // End of variables declaration//GEN-END:variables
}
