/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fingerlime.gui.form606;

import fingerlime.gui.contribuyentes.*;

/**
 *
 * @author victor
 */
public class FrmEditor606 extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmEditor606() {
//        this.setLocationRelativeTo(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnCargarArchivo = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        panelList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelTareas = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contribuyentes");

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setMinimumSize(new java.awt.Dimension(608, 50));
        panelSuperior.setPreferredSize(new java.awt.Dimension(0, 45));
        panelSuperior.setLayout(new java.awt.GridLayout(1, 0));

        panelTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(57, 105, 138));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/expensive_24.png"))); // NOI18N
        lblTitulo.setText("Remision Costos y Gastos (606)");
        panelTitulo.add(lblTitulo);

        panelSuperior.add(panelTitulo);

        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/save_16.png"))); // NOI18N
        jButton2.setText("Guardar");
        panelBotones.add(jButton2);

        btnCargarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/import_16.png"))); // NOI18N
        btnCargarArchivo.setText("Importar");
        panelBotones.add(btnCargarArchivo);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/export_16.png"))); // NOI18N
        btnNuevo.setText("Exportar");
        panelBotones.add(btnNuevo);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/close_16.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelBotones.add(btnCerrar);

        panelSuperior.add(panelBotones);

        panelPrincipal.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setLayout(new java.awt.BorderLayout());

        panelList.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelList.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelTareas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelTareas.setPreferredSize(new java.awt.Dimension(858, 135));

        jLabel1.setText("Nombre del Contribuyente");

        jLabel2.setText("RNC");

        jLabel3.setText("Periodo");

        jButton1.setText("Explorar");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/add_16.png"))); // NOI18N
        jButton3.setText("Agregar Registro");

        javax.swing.GroupLayout panelTareasLayout = new javax.swing.GroupLayout(panelTareas);
        panelTareas.setLayout(panelTareasLayout);
        panelTareasLayout.setHorizontalGroup(
            panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTareasLayout.createSequentialGroup()
                        .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panelTareasLayout.createSequentialGroup()
                                .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelTareasLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        panelTareasLayout.setVerticalGroup(
            panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTareasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTareasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelList.add(panelTareas, java.awt.BorderLayout.PAGE_START);

        panelCentral.add(panelList, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelList;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTareas;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
