/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fingerlime.gui.reporteCyG;

import fingerlime.gui.contribuyentes.*;
import java.util.ArrayList;
import java.util.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import fingerlime.models.ReporteCyG;
import fingerlime.models.RegistroReporteCyG;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victor
 */
public class FrmEditorReporteCyG extends javax.swing.JDialog {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmEditorReporteCyG() {
//        this.setLocationRelativeTo(this);
        this.setModal(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fchArchivo = new javax.swing.JFileChooser();
        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnCargarArchivo = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        panelList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistros = new javax.swing.JTable();
        panelTareas = new javax.swing.JPanel();
        txtNombreContribuyente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtRNC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        comboAnio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboMes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FingerLime");

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setMinimumSize(new java.awt.Dimension(608, 50));
        panelSuperior.setPreferredSize(new java.awt.Dimension(0, 45));
        panelSuperior.setLayout(new java.awt.GridLayout(1, 0));

        panelTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(57, 105, 138));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/expensive_24.png"))); // NOI18N
        lblTitulo.setText("Remision Costos y Gastos (606)");
        panelTitulo.add(lblTitulo);

        panelSuperior.add(panelTitulo);

        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/save_16.png"))); // NOI18N
        jButton2.setText("Guardar");
        panelBotones.add(jButton2);

        btnCargarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/import_16.png"))); // NOI18N
        btnCargarArchivo.setText("Importar");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });
        panelBotones.add(btnCargarArchivo);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/export_16.png"))); // NOI18N
        btnNuevo.setText("Exportar");
        panelBotones.add(btnNuevo);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/close_16.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelBotones.add(btnCerrar);

        panelSuperior.add(panelBotones);

        panelPrincipal.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        panelCentral.setLayout(new java.awt.BorderLayout());

        panelList.setLayout(new java.awt.BorderLayout());

        tableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proveedor", "RNC", "NFC", "Monto Total"
            }
        ));
        jScrollPane1.setViewportView(tableRegistros);

        panelList.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelTareas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelTareas.setPreferredSize(new java.awt.Dimension(858, 135));

        jLabel1.setText("Nombre del Contribuyente");

        jLabel2.setText("RNC");

        jLabel3.setText(" Año");

        jButton1.setText("Explorar");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/add_16.png"))); // NOI18N
        jButton3.setText("Agregar Registro");

        comboAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2018", "2017", "2016", "2015", "2014" }));

        jLabel4.setText("Mes");

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        javax.swing.GroupLayout panelTareasLayout = new javax.swing.GroupLayout(panelTareas);
        panelTareas.setLayout(panelTareasLayout);
        panelTareasLayout.setHorizontalGroup(
            panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTareasLayout.createSequentialGroup()
                        .addComponent(txtNombreContribuyente, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jLabel1)
                    .addGroup(panelTareasLayout.createSequentialGroup()
                        .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRNC, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTareasLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel4))
                            .addGroup(panelTareasLayout.createSequentialGroup()
                                .addComponent(comboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelTareasLayout.setVerticalGroup(
            panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(panelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreContribuyente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelList.add(panelTareas, java.awt.BorderLayout.PAGE_START);

        panelCentral.add(panelList, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        ReporteCyG f606 = new ReporteCyG();
        fchArchivo.showOpenDialog(this);
        List<String> lineas = new ArrayList<>();
        File f = fchArchivo.getSelectedFile();
        
        if (f != null) {
            try {
                BufferedReader bfReader = new BufferedReader(new FileReader(f));
                String linea = "";
                while ((linea = bfReader.readLine()) != null) {
                    lineas.add(linea);
                }
                bfReader.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FrmEditorReporteCyG.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FrmEditorReporteCyG.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        f606.cargarDesdeArregloTxt(lineas);
        this.txtRNC.setText(f606.getRnc());
        this.txtNombreContribuyente.setText(f606.getNombreContribuyente());
        JOptionPane.showMessageDialog(this, f606.getRegistros().get(0).getMontoFacturadoBienes());
        
        DefaultTableModel model = ( DefaultTableModel)this.tableRegistros.getModel();
        for(RegistroReporteCyG registro : f606.getRegistros()){
            model .addRow(new Object[]{registro.getNombreProveedor(),registro.getRncProveedor(),registro.getNfc(),registro.getTotalMontoFacturado()});
        }
        
        this.tableRegistros.setModel(model);
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> comboAnio;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JFileChooser fchArchivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelList;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTareas;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tableRegistros;
    private javax.swing.JTextField txtNombreContribuyente;
    private javax.swing.JTextField txtRNC;
    // End of variables declaration//GEN-END:variables
}
