/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fingerlime.gui.contribuyentes;

/**
 *
 * @author victor
 */
public class FrmContribuyentes extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmContribuyentes() {
//        this.setLocationRelativeTo(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        panelList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelTareas = new javax.swing.JPanel();
        btnBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contribuyentes");

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(102, 102, 102));
        panelSuperior.setPreferredSize(new java.awt.Dimension(0, 35));
        panelSuperior.setLayout(new java.awt.GridLayout());

        panelTitulo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(57, 105, 138));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/group_24.png"))); // NOI18N
        lblTitulo.setText("Contribuyentes");
        panelTitulo.add(lblTitulo);

        panelSuperior.add(panelTitulo);

        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/close_16.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelBotones.add(btnCerrar);

        panelSuperior.add(panelBotones);

        panelPrincipal.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setLayout(new java.awt.BorderLayout());

        panelList.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelList.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelCentral.add(panelList, java.awt.BorderLayout.CENTER);

        panelTareas.setPreferredSize(new java.awt.Dimension(858, 40));
        panelTareas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnBusqueda.setPreferredSize(new java.awt.Dimension(200, 27));
        panelTareas.add(btnBusqueda);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/search_16.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        panelTareas.add(btnBuscar);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fingerlime/gui/images/plus_16.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        panelTareas.add(btnNuevo);

        panelCentral.add(panelTareas, java.awt.BorderLayout.PAGE_START);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField btnBusqueda;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelList;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTareas;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
